import { Open_Sans } from "next/font/google";
import Sidebar from "../components/Sidebar";

const open_sans = Open_Sans({ subsets: ["latin"] });
export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function TaskLayout({ children }) {
    return (
        <div className={`${open_sans.className} h-screen w-full bg-[#F3F6F9]`}>
                <Sidebar />
                <main className="py-10 lg:pl-72">
                    <div className="px-4 sm:px-6 lg:px-8">{children}</div>
                </main>
        </div>
    );
}
